name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false
  NFT_MAX_SHARDS: 5
  SOURCE_BRANCH: ${{ github.head_ref || github.ref_name }}
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test_all:
    name: Run ${{ matrix.filter }} tests | shard ${{ matrix.shard }} (${{ matrix.NXF_VER }})
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-cmgg/exomecnv') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "24.10.0"
          - "latest-everything"
        tags:
          - "modules_local"
          - "pipeline"
          - "pipeline"
        shard: [1, 2, 3, 4, 5]
    steps:
      - name: Free some space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      # - name: Disk space cleanup
      #   uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Install nf-test
        run: |
          conda install -c bioconda nf-test

      - name: "Run ${{ matrix.tags }} tests (changed) | ${{ matrix.shard }}/${{ env.NFT_MAX_SHARDS }}"
        if: ${{ env.SOURCE_BRANCH != 'master' }}
        run: |
          $CONDA/bin/nf-test test \
            --ci \
            --changed-since HEAD^ \
            --shard ${{ matrix.shard }}/${{ env.NFT_MAX_SHARDS }} \
            --tag ${{ matrix.tags }} \
            --junitxml=default.xml

      - name: "Run ${{ matrix.tags }} tests (all) | ${{ matrix.shard }}/${{ env.NFT_MAX_SHARDS }}"
        if: ${{ env.SOURCE_BRANCH == 'master' }}
        run: |
          $CONDA/bin/nf-test test \
            --ci \
            --shard ${{ matrix.shard }}/${{ env.NFT_MAX_SHARDS }} \
            --tag ${{ matrix.tags }} \
            --junitxml=default.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "default.xml"

      - name: Upload log file artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: nf-test-workdir
          path: .nf-test/
